version: "3"

volumes:
  db:
  logs:

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - "db:/data/db"

  bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: 0xb1b1/itam-bot:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "logs:/data"
    depends_on:
      - db
