version: "3"

services:
  db:
    container_name: itam-bot-psql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    # ports:
    #   - "6961:5432"  #! Testing only!
    networks:
      - itambot-network

  itam-bot:
    container_name: itam-bot
    build:
      context: ./src
      dockerfile: Dockerfile
    image: 0xb1b1/itam-bot
    restart: always
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      DEFAULT_ADMIN_UID: ${DEFAULT_ADMIN_UID}
      DEFAULT_ADMIN_USERNAME: ${DEFAULT_ADMIN_USERNAME}
      SUPERADMIN_UIDS: ${SUPERADMIN_UIDS}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB:   ${PG_DB}
    volumes:
      - ./docker/itam-bot:/data
    networks:
      - itambot-network
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: itam-bot-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "23439:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    networks:
      - itambot-network
    depends_on:
      - db

networks:
  itambot-network:
    name: itambot-network
