version: "3"

volumes:
  db:
  logs:

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - "db:/var/lib/postgresql/data"

  bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: 0xb1b1/itam-bot:latest
    restart: always
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      DEFAULT_ADMIN_UID: ${DEFAULT_ADMIN_UID}
      DEFAULT_ADMIN_USERNAME: ${DEFAULT_ADMIN_USERNAME}
      SUPERADMIN_UIDS: ${SUPERADMIN_UIDS}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB:   ${PG_DB}
    volumes:
      - "logs:/data"
    depends_on:
      - db
