#!/usr/bin/env python3

"""Sticker IDs."""

WELCOME = "CAACAgQAAxkBAAIBnmQg2QL27SvkQAwtghcQqvmCxfGZAALMAAPOOQgN32d8ZX5EuWQvBA"
YANDEX_INTERNSHIP_START = "CAACAgIAAxkBAAID3WQiDTx4_ox1-YKnWyuxqdkOcXqMAAJJKQACSCeRSEaNSR29Kx7rLwQ"
